name: Render Quarto PDF (Simple)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Quarto PDF (HTML-based)
      run: quarto render report.qmd --to pdf-simple

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: rendered-pdf
        path: report.pdf
